[package]
name = "mini-async-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "1.13.0"
polling = "2.8.0"
scoped-tls = "1.0.1"
